<table width="1010" border="0" cellspacing="0" cellpadding="0">
<tr><td style="padding-top:10px">Россия, Пермь, ул. Клары Цеткин, 9. Тел./факс (342) 238-76-78.</td><td align="right" style="padding-top:10px"><a href="mailto:team@alternativaplatform.com">team@alternativaplatform.com</a></td>
<tr>
<td colspan="2" class="bottom" style="padding-top:10px">
&copy; 2007-2010 ООО &laquo;Альтернатива&raquo;. Все права защищены.<br>
Использование данной веб-страницы подразумевает ваше согласие с <a href="/ru/terms_of_use/">Правилами пользования</a> и <a href="/ru/privacy_policy/">Политикой конфиденциальности</a>.

</td>

</tr>
</table>
<img src="../img/spacer.gif" width="1" height="20">
</center>
<div style="position:absolute; top:0; left:0px; z-index:1;"><a href="http://flashawards.ru/" target="_blank"><img src="../img/rfa.png" border="0" /></a></div>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-2354052-1");
pageTracker._initData();
pageTracker._trackPageview(); 
</script>
</body>
</html>
